
export const LOAD_PROJECTS_ALL = 'LOAD_PROJECTS_ALL';
export const UPDATE_PROJECT_SUMMARY = 'UPDATE_PROJECT_SUMMARY';
export const DELETE_PROJECT_SUMMARY = 'DELETE_PROJECT_SUMMARY';
export const ADD_PROJECT_SUMMARY ='ADD_PROJECT_SUMMARY';

export const LOAD_SINGLE_PROJECT = 'LOAD_SINGLE_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const LOAD_LOCATIONS_ALL = 'LOAD_LOCATIONS_ALL';
export const LOAD_DISCIPLINES = 'LOAD_DISCIPLINES';
export const LOAD_EXPERIENCES = 'LOAD_EXPERIENCES';

export const LOAD_USERS_ALL = 'LOAD_USERS_ALL';
export const UPDATE_USER_SUMMARIES ='UPDATE_USER_SUMMARIES';
export const LOAD_USERS_SPECIFIC = 'LOAD_USERS_SPECIFIC';
export const UPDATE_USERS_SPECIFIC = 'UPDATE_USERS_SPECIFIC';

export const LOAD_MASTERLIST = 'LOAD_MASTERLIST';
export const CREATE_DISCIPLINE = 'CREATE_DISCIPLINE';
export const CREATE_SKILL = 'CREATE_SKILL';
export const CREATE_PROVINCE = 'CREATE_PROVINCE';
export const CREATE_CITY = 'CREATE_CITY';

export const PERFORM_USER_SEARCH = 'PERFORM_USER_SEARCH';
export const DELETE_DISCIPLINE = 'DELETE_DISCIPLINE';
export const DELETE_SKILL = 'DELETE_SKILL';
export const DELETE_PROVINCE = 'DELETE_PROVINCE';
export const DELETE_CITY = 'DELETE_CITY';
