
export const LOAD_PROJECTS_ALL = 'LOAD_PROJECTS_ALL';
export const CREATE_PROJECT_SUMMARY = 'CREATE_PROJECT_SUMMARY';
export const UPDATE_PROJECT_SUMMARY = 'UPDATE_PROJECT_SUMMARY';
export const DELETE_PROJECT_SUMMARY = 'DELETE_PROJECT_SUMMARY';

export const LOAD_SINGLE_PROJECT = 'LOAD_SINGLE_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const LOAD_LOCATIONS_ALL = 'LOAD_LOCATIONS_ALL';
export const LOAD_DISCIPLINES = 'LOAD_DISCIPLINES';
export const LOAD_EXPERIENCES = 'LOAD_EXPERIENCES';

export const LOAD_USERS_ALL = 'LOAD_USERS_ALL';
export const LOAD_USERS_SPECIFIC = 'LOAD_USERS_SPECIFIC';
export const UPDATE_USERS_SPECIFIC = 'UPDATE_USERS_SPECIFIC';

export const LOAD_MASTERLIST = 'LOAD_MASTERLIST';
export const LOAD_MASTERLIST_PENDING = 'LOAD_MASTERLIST';
