export const LOAD_USERS_ALL = 'LOAD_USERS_ALL';
export const LOAD_PROJECTS_ALL = 'LOAD_PROJECTS_ALL';
export const LOAD_PROJECTS_MOST_RECENT = 'LOAD_PROJECTS_MOST_RECENT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const LOAD_LOCATIONS_ALL = 'LOAD_LOCATIONS_ALL';
export const LOAD_DISCIPLINES = 'LOAD_DISCIPLINES';
